name: eko-devsecops-cicd

#evento
on:
    push:
        branches:
            - develop

jobs:
    secret:
        name: Secret Security Scan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: '0' #historia git
            - name: scan gitleaks
              run: |
                echo "scan gitleak"
                docker run --rm -v "$(pwd):/pwd" zricethezav/gitleaks:latest detect --verbose --source "/pwd" --report-format=sarif --report-path=/pwd/gitleaks-result.sarif --log-level=debug
              continue-on-error: true 
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.13' 
            - name: remove items duplicados
              run: |
                mv gitleaks-result.sarif /tmp/gitleaks-result.sarif
                python .github/scripts/remove.py /tmp/gitleaks-result.sarif
                mv /tmp/gitleaks-result.sarif gitleaks-result.sarif 
              continue-on-error: true 
            - name: upload report
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: gitleaks-result.sarif
                category: gitleak
              continue-on-error: true 
    trivy:
        name: Container Security Scan
        needs: secret
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: '0' #historia git
            - name: build images
              run: docker build -t app-image:${{ github.sha }} .

            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              env:
                TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
              with:
                image-ref: 'app-image:${{ github.sha }}'
                format: 'sarif'
                output: 'trivy-results.sarif'
                severity: 'CRITICAL,HIGH'

              continue-on-error: true 
            - name: upload report
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: trivy-results.sarif
                category: trivy                