name: eko-pipeline-security-tab

on:
  push:
    branches:
      - develop

permissions:
  security-events: write
  actions: read
  contents: read
  checks: write
  pull-requests: write

env:
  DEFECTDOJO_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
  REGISTRY: ${{ secrets.DOCKER_USERNAME }}
  REPOSITORY: ${{ github.event.repository.name }}

jobs:
  secrets:
    name: Secrets Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Scan with Gitleaks
        run: |
          docker run --rm \
            -v "$(pwd):/pwd" \
            zricethezav/gitleaks:latest \
            detect \
            --verbose \
            --source="/pwd" \
            --report-format=json \
            --report-path=/pwd/gitleaks-results.json \
            --log-level=debug \
            --config=/pwd/.gitleaks.toml
        continue-on-error: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'            
      - uses: actions/upload-artifact@v4
        with:
          name: gitleaks
          path: gitleaks-results.json
      - name: upload defectDojo
        run: | 
          pip install requests
          python .github/scripts/upload-reports.py gitleaks-results.json
  
  sca:
    runs-on: ubuntu-latest
    name: Sca Security Scan
    steps:
      - name: Checkout action
        uses: actions/checkout@v4     
      - name: Snyk SCA Analysis
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --sarif-file-output=snyk-results.json
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: snyk
          path: snyk-results.json
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'    
      - name: upload defectDojo
        run: | 
          pip install requests
          python .github/scripts/upload-reports.py snyk-results.json     
  container-scan:
    runs-on: ubuntu-latest
    name: Container Security Scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t app-image:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
        with:
          image-ref: 'app-image:${{ github.sha }}'
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH'
      - uses: actions/upload-artifact@v4
        with:
          name: trivy
          path: trivy-results.json
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'    
      - name: upload defectDojo
        run: | 
          pip install requests
          python .github/scripts/upload-reports.py trivy-results.json  
          
  build:
    runs-on: ubuntu-latest
    name: build docker
    needs: [secrets,sca,container-scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Docker  
        uses: docker/setup-buildx-action@v3.7.1
      - uses: docker/login-action@v3.3.0
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker build
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          push: true
          tags: |
             ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest,
             ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    name: deploy
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_IP_EC2 }}
          username: ${{ secrets.AWS_USER_EC2 }}
          key: ${{ secrets.AWS_TOKEN_EC2 }}
          port: ${{ secrets.AWS_PORT_EC2 }}
          source: "docker-compose.yml"
          target: "~/app"
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AWS_IP_EC2 }}
          username: ${{ secrets.AWS_USER_EC2 }}
          key: ${{ secrets.AWS_TOKEN_EC2 }}
          port: ${{ secrets.AWS_PORT_EC2 }}
          script: |
            cd ~/app
            docker-compose up -d